name: mtb
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=2.18.0<3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  persistent_bottom_nav_bar: ^5.0.2
  get: ^4.6.5
  shared_preferences: ^2.2.0
  dropdown_button2: ^2.1.3
  flutter_svg: ^2.0.7
  get_storage:
  google_sign_in:
  intl:
  internet_connection_checker:
  connectivity_plus:
  share_plus: ^7.1.0
  fluttertoast: ^8.2.2
  lottie:
  sms_autofill: ^2.3.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_styled_toast:
  flutter_svprogresshud:
  flutter_facebook_auth:
  image_picker:
  permission_handler:
  image_compression_flutter:
  image_gallery_saver: ^1.7.1
  rflutter_alert: ^2.0.4
  twitter_login: ^4.4.2
  firebase_core: ^2.15.1
  firebase_auth:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/authFlow/
   - assets/homeFlow/
   - assets/common/
   - assets/searchFlow/
   - assets/profileFlow/
   - assets/following/
   - assets/trending/
   - assets/searchFilter/